ticker_map = {
    'us_durable_goods_new_orders': {'program': 'M3ADV',
                                    'categories': 'MDM',
                                    'dataType': 'NO'},
    'us_durable_goods_shipments': {'program': 'M3ADV',
                                   'categories': 'MDM',
                                   'dataType': 'VS'},
    'us_retail_sales': {'program': 'MRTS',
                        'categories': '44X72',
                        'dataType': 'SM'},
    'us_new_home_sales': {'program': 'RESSALES',
                          'categories': 'ASOLD',
                          'dataType': 'TOTAL'},
    'us_housing_starts': {'program': 'RESCONST',
                          'categories': 'ASTARTS',
                          'dataType': 'TOTAL'},
    'us_external_balance': {'program': 'FTD',
                            'categories': 'BOPGS',
                            'dataType': 'BAL'}
}
